# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 281e8cfac151d5f4b13071b0393ee76205333454c4f052a2bbe867893e0617da81852eafd7d7fc635e3dbca651329e6cd8cd8b0698555044869dc709f159ab4d

test:
  secret_key_base: 506e3f5f514030b1876e873b2584d5bb4055afc7fad5ca7a0e4f2e20645d7ba869d2728d7b291d9dd4843d1cf52b659795a2a56509bbfa648524572296389554

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
